services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 1880:1880
    volumes:
      - ./data/node-red-data:/data
    networks:
      - driver_network

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=driver
      - DOCKER_INFLUXDB_INIT_PASSWORD=driver_password
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=myadmintoken
    depends_on:
      - node-red
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - driver_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=driver
      - GF_SECURITY_ADMIN_PASSWORD=driver_password
    volumes:
      - ./data/grafana_data:/var/lib/grafana
    networks:
      - driver_network


volumes:
  node-red-data:
  influxdb-data:
  grafana_data:

networks:
  driver_network: